### ISSUE TITLE
What do I do?

### ISSUE THREAD

**Issue by AirmanRNC** [Shizmob/rpatool#19]
![image](https://user-images.githubusercontent.com/82128569/200193882-7142208a-a650-4c2a-a384-6fd1701139e5.png)

**Comment by UniverseDevel** [comment]
Is rpatool script inside game directory? Do you have python installed? If both are yes, then you should call script as `python rpatool -x archive.rpa` else we need more details.

The easiest way how not to mess up when you are not sure what you are doing is using absolute paths for everything:

`python "C:\<PATH TO RPATOOLS>\rpatool" -x "C:\<PATH TO ARCHIVE>\archive.rpa"`

**Comment by AirmanRNC** [comment]
![image](https://user-images.githubusercontent.com/82128569/200214696-e7a057c5-b9cd-4c9d-8a8c-4fbb96455b76.png)

**Comment by UniverseDevel** [comment]
Use absolute paths then. It is apparent that rpatool script is not inside the same directory as you placed yourself (game directory). You need to call the script from same location that you plced it it. Please provide full path in text form to where your rpatool script is located and full path to this archive to give you correct command. Otherwise you have to find solution for yourself.

**Comment by UniverseDevel** [comment]
https://www.wikihow.com/Use-Windows-Command-Prompt-to-Run-a-Python-File
